### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jlauinger** [jlauinger/ficha#1]
- [x] CSV import tests
 - [x] CSV export
 - [x] add new cards smoothly
 - [x] actually consistent CollectionsService
 - [x] local storage persistence
 - [x] backend service
